services:
  lidar-standalone:
    image: 010497/lidar-studio:latest
    container_name: lidar-standalone
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - config:/config
      - recordings:/recordings

volumes:
  config:
  recordings: