services:
  lidar-standalone:
    image: 010497/lidar-studio:latest-amd64
    container_name: lidar-standalone
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - config:/app/config
      - recordings:/app/recordings

volumes:
  config:
  recordings: